name: swampert

services:
  storage:
    env_file: .env.local
    container_name: storage
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    networks:
      - swampert-network
    volumes:
      - swampert-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  swampert-data:
    driver: local
    name: swampert-data

networks:
  swampert-network:
    driver: bridge
    name: swampert-network
